LAUNCH_METHOD: '0' #0=Menu, 1=Movie libraries, 2=TV Show libraries, 3=Both consecutively
PLEX_URL: 'http://localhost:32400'
PLEX_TOKEN: 'YOUR_PLEX_TOKEN'
USE_LABELS: false

# TV Libraries Configuration
# Configure multiple TV show libraries with individual genre skip lists
# Each library can have different genres_to_skip settings
TV_LIBRARIES:
  - name: 'TV Shows'
    genres_to_skip:
      - 'Talk Show'
      - 'Stand-Up'
      - 'News'
  - name: 'Anime TV'
    genres_to_skip:
      - 'Talk Show'
      - 'Stand-Up'
      - 'News'
      - 'Reality'
  - name: 'Documentaries'
    genres_to_skip:
      - 'Talk Show'
      - 'Stand-Up'

# Movie Libraries Configuration
# Configure multiple movie libraries with individual genre skip lists
# Each library can have different genres_to_skip settings
MOVIE_LIBRARIES:
  - name: 'Movies'
    genres_to_skip:
      - 'Short'
      - 'Stand-Up'
      - 'Concert'
  - name: 'Anime Movies'
    genres_to_skip:
      - 'Short'
      - 'Stand-Up'
      - 'Concert'
  - name: 'Documentaries'
    genres_to_skip:
      - 'Short'
      - 'Stand-Up'

CHECK_PLEX_PASS_TRAILERS: true
DOWNLOAD_TRAILERS: true
PREFERRED_LANGUAGE: original
REFRESH_METADATA: true
SHOW_YT_DLP_PROGRESS: false
YT_DLP_COOKIES_FROM_BROWSER: "chrome"  # or firefox, edge, safari, etc.
YT_DLP_COOKIES_FILE: "/path/to/your/cookies.txt"
MAP_PATH: false
PATH_MAPPINGS:
  "/media": "P:/media"